
url     : "https://deut-erium.github.io"
baaseurl: ""

theme: jekyll-theme-midnight
title: This is Truely Yours
description: Feel free to remove the 'e' and become a truly! 


## => Language and Timezone
##############################
lang: en
timezone: Asia/Kolkata
future: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-postfiles
  - jekyll-seo-tag